package team.finder.api.teams

enum class Language {
    am, // Amharic
    ar, // Arabic
    eu, // Basque
    bn, // Bengali
    en, // English
    `pt-BR`, // Portuguese_Brazil
    bg, // Bulgarian
    ca, // Catalan
    chr, // Cherokee
    hr, // Croatian
    cs, // Czech
    da, // Danish
    nl, // Dutch
    et, // Estonian
    fil, // Filipino
    fi, // Finnish
    fr, // French
    de, // German
    el, // Greek
    gu, // Gujarati
    iw, // Hebrew
    hi, // Hindi
    hu, // Hungarian
    `is`, // Icelandic
    id, // Indonesian
    it, // Italian
    ja, // Japanese
    kn, // Kannada
    ko, // Korean
    lv, // Latvian
    lt, // Lithuanian
    ms, // Malay
    ml, // Malayalam
    mr, // Marathi
    no, // Norwegian
    pl, // Polish
    `pt-PT`, // Portuguese_Portugal
    ro, // Romanian
    ru, // Russian
    sr, // Serbian
    `zh-CN`, // Chinese_PRC
    sk, // Slovak
    sl, // Slovenian
    es, // Spanish
    sw, // Swahili
    sv, // Swedish
    ta, // Tamil
    te, // Telugu
    th, // Thai
    `zh-TW`, // Chinese_Taiwan
    tr, // Turkish
    ur, // Urdu
    uk, // Ukrainian
    vi, // Vietnamese
    cy, // Welsh
    ot; // Other
}
