/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package team.finder.api

import io.micrometer.core.instrument.Clock
import io.micrometer.core.instrument.MeterRegistry
import io.micrometer.core.instrument.Metrics
import io.micrometer.jmx.JmxConfig
import io.micrometer.jmx.JmxMeterRegistry
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.cache.annotation.EnableCaching
import org.springframework.context.annotation.Bean


@SpringBootApplication
@EnableCaching
class App {

    @Bean
    fun init() {
        val registry: MeterRegistry = JmxMeterRegistry(JmxConfig.DEFAULT, Clock.SYSTEM)
        Metrics.addRegistry(registry)
    }
}

fun main() {
    runApplication<App>()
}
