/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package team.finder.api

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    runApplication<App>()
}
