name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - run: ./gradlew build && ./gradlew jar

      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs
