name: Java CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build JAR
        run: ./gradlew build && ./gradlew jar

      - name: Upload artifact to Workflow
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: ${{ github.workspace }}/app/build/libs/app.jar

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key

      - name: Deploy to server
        run: |
          scp ${{ github.workspace }}/app/build/libs/app.jar pipeline@178.62.53.195:${{ secrets.API_JAR_LOCATION }}
          systemctl restart team-finder-api.service
        shell: bash
        env:
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
